# -*- coding: utf-8 -*-
"""scratchpad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/empty.ipynb
"""

import pandas as pd


df = pd.read_excel('formulary2.xlsx')

# Add a new column "1st_letter" using the first letter of "商品學名"
df['1st_letter'] = df['商品學名'].str[0]

# Group by "1st_letter" and sort 商品學名 within each group
grouped_df = df.sort_values('商品學名').groupby('1st_letter')

# Write the grouped data to a Markdown file
with open('index.md', 'w') as file:
    file.write("# 索引\n\n")
    for first_letter, first_letter_df in grouped_df:
        file.write(f"## {first_letter}\n")
        for _, row in first_letter_df.iterrows():
            file.write(f"* {row['商品學名']}\n")
            file.write("  " + f"* {row['商品英文名稱']}\n")
        file.write("\n")
